### ISSUE TITLE
plans to expose other variants?

### ISSUE THREAD

**Issue by evq** [aead/argon2#1]
hey @aead!

thanks for your work on a golang implementation of argon2 and on upstreaming it to `x/crypto`.

I was hoping to make use of `argon2d` as a key derivation function for a personal key backup exercise. it seems better suited for my use case as I will only use it on an offline device where there is little possibility of side channel attacks and furthermore afaict currently known speedup attacks only apply to `argon2i`.

I noticed while it seems there is support and a test for `argon2d`, only `argon2i` is exposed publicly from this package. are there any plans to change this? thanks again!

**Comment by aead** [comment]
Hi @evq 
There is a [RFC-draft](https://tools.ietf.org/html/draft-irtf-cfrg-argon2-03) for argon2. I will send a patch to `x/crypto` as soon as the draft is accepted. However the draft recommends Argon2id because of the time-memory attack bounds in contrast to the Argon2 paper which recommends Argon2i. 
So I guess `x/crypto` will publicly expose Argon2i (`Key`) and Argon2id (`KeyRFC` or something similar). Whether `x/crypto` should expose Argon2d additionally must be decided by Adam Langley. 

However I can expose Argon2d and Argon2id here. Than you can decide whether you want to:
1. Use Argon2d and risk to not being able to switch over to `x/crypto` easily if the Go-Team decides to
   not support Argon2d - for example because of API complexity.
2. Use Argon2id which will probably be part of `x/crypto` (although I can't promise). So you would be able to switch over easily by changing import and maybe renaming the function.

**Comment by evq** [comment]
I exported 2d locally to compare results against cgo bindings to the C reference implementation, looked good to me :) Will be happy to switch back to your upstream, thanks for the fast reply and change!

I think I will proceed with using 2d. It would be nice if it can eventually be upstreamed to `x/crypto` but it is not essential for my exercise. Knowing that even if this repo were to disappear I could fork `x/crypto` and expose it myself is enough for me, I mainly wanted to make sure I wasn't using parameters that weren't expected to work.

Thanks again!
